# Generated by Django 5.0.1 on 2025-05-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_medicalrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="prescription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="prescription_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
